# Generated by Django 5.1.3 on 2024-11-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='is_deleted',
        ),
    ]
