# Generated by Django 5.1.3 on 2024-11-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='s_name',
            new_name='name',
        ),
    ]
